name: Scorecards supply-chain security
on:
  workflow_dispatch:
jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    steps:
      - name: scorecards
        uses: aps831/workflows/.github/workflows/scorecards.yaml@feat/openssf
